FROM pytorch/pytorch:2.4.1-cuda11.8-cudnn9-devel

RUN apt-get update && apt-get install -y libgl1-mesa-glx libpci-dev curl nano psmisc zip git && apt-get --fix-broken install -y

RUN conda install -y scikit-learn pandas flake8 yapf isort yacs future libgcc

RUN pip install --upgrade pip && python -m pip install --upgrade setuptools

RUN pip install absl-py==1.4.0 
RUN pip install addict==2.4.0 
RUN pip install aiohttp==3.8.4 
RUN pip install aiosignal==1.3.1 
RUN pip install aliyun-python-sdk-core==2.13.36 
RUN pip install aliyun-python-sdk-kms==2.16.1 
RUN pip install antlr4-python3-runtime==4.9.3 

RUN pip install appdirs==1.4.4 
RUN pip install astunparse==1.6.3 
RUN pip install async-timeout==4.0.2 
RUN pip install asynctest==0.13.0 
RUN pip install cachetools==5.3.0 
RUN pip install chardet==3.0.4 
RUN pip install charset-normalizer==2.0.12 

RUN pip install click==8.1.3 
RUN pip install colorama==0.4.6 
RUN pip install contextlib2==21.6.0 
RUN pip install cox==0.1.post3 
RUN pip install crcmod==1.7 
RUN pip install cryptography==41.0.1 
RUN pip install cycler==0.11.0 

RUN pip install cython==3.0.2 
RUN pip install descartes==1.1.0 
RUN pip install dill==0.3.7 
RUN pip install docker-pycreds==0.4.0 
RUN pip install einops==0.6.1 
RUN pip install et-xmlfile==1.1.0 
RUN pip install filelock==3.8.2 
RUN pip install flatbuffers==23.5.26 
RUN pip install fonttools==4.38.0 

RUN pip install frozenlist==1.3.3 

RUN pip install fsspec==2023.1.0 
RUN pip install ftfy==6.1.1 
RUN pip install future==0.18.3 
RUN pip install fvcore==0.1.5.post20221221
RUN pip install gast==0.4.0
RUN pip install gdown==4.7.1
RUN pip install geotorch==0.3.0
RUN pip install gitdb==4.0.10
RUN pip install gitpython==3.1.31
RUN pip install google-auth==2.17.3 

RUN pip install google-auth-oauthlib==0.4.6
RUN pip install google-pasta==0.2.0
RUN pip install googleapis-common-protos==1.62.0
RUN pip install gputil==1.4.0
RUN pip install grad-cam==1.4.8
RUN pip install grpcio==1.54.0
RUN pip install huggingface-hub==0.16.4
RUN pip install hydra-core==1.3.2
RUN pip install idna==2.10
RUN pip install imageio==2.31.1
RUN pip install iopath==0.1.8
RUN pip install ipywidgets==8.0.6
RUN pip install jinja2==2.11.3
RUN pip install jmespath==0.10.0
RUN pip install joblib==1.2.0
RUN pip install jsonpatch==1.32
RUN pip install jsonpointer==2.3
RUN pip install jupyter==1.0.0
RUN pip install jupyter-console==6.6.3
RUN pip install jupyter-core==4.12.0
RUN pip install jupyterlab-widgets==3.0.7
RUN pip install keras==2.11.0
RUN pip install kiwisolver==1.4.4
RUN pip install libclang==16.0.6
RUN pip install lightning-utilities==0.9.0
RUN pip install littleutils==0.2.2
RUN pip install lmdb==1.4.1
RUN pip install markdown==3.4.3
RUN pip install markdown-it-py==2.2.0
RUN pip install markupsafe==2.1.5
RUN pip install mdurl==0.1.2
RUN pip install medpy==0.4.0
RUN pip install mizani==0.7.3
RUN pip install ml-collections==0.1.1
RUN pip install mmcls==0.25.0
RUN pip install mmdet==3.0.0
RUN pip install mmengine==0.7.3
RUN pip install mock==5.1.0
RUN pip install model-index==0.1.11
RUN pip install multidict==6.0.4
RUN pip install munch==4.0.0
RUN pip install networkx==2.6.3
RUN pip install nose==1.3.7
RUN pip install numexpr==2.8.6
RUN pip install oauthlib==3.2.2
RUN pip install ogb==1.3.6
RUN pip install omegaconf==2.3.0
RUN pip install open-clip-torch==2.7.0
RUN pip install opendatalab==0.0.10
RUN pip install openmim==0.3.9 

RUN pip install openpyxl==3.1.2
RUN pip install opt-einsum==3.3.0
RUN pip install ordered-set==4.1.0
RUN pip install oss2==2.17.0
RUN pip install palettable==3.3.3
RUN pip install pathtools==0.1.2
RUN pip install patsy==0.5.3
RUN pip install pillow==9.3.0
RUN pip install pip==24.0
RUN pip install plotnine==0.8.0
RUN pip install portalocker==2.7.0
RUN pip install pretrainedmodels==0.7.4
RUN pip install prettytable==3.7.0
RUN pip install promise==2.3
RUN pip install prompt-toolkit==3.0.38
RUN pip install protobuf==3.19.6
RUN pip install py3nvml==0.2.7
RUN pip install pyasn1==0.5.0
RUN pip install pyasn1-modules==0.3.0
RUN pip install pycocotools==2.0.6
RUN pip install ruamel-yaml==0.18.5
RUN pip install ruamel-yaml-clib==0.2.8
RUN pip install scikit-image==0.19.3
RUN pip install scikit-learn==1.0.2
RUN pip install scipy==1.7.1
RUN pip install sconf==0.2.5
RUN pip install seaborn==0.12.2
RUN pip install sentencepiece==0.1.99
RUN pip install sentry-sdk==1.9.0
RUN pip install setproctitle==1.3.2
RUN pip install shapely==2.0.1
RUN pip install simpleitk==2.3.0
RUN pip install simplejson==3.19.2
RUN pip install smmap==5.0.0
RUN pip install 
RUN pip install statsmodels==0.13.5
RUN pip install tables==3.7.0
RUN pip install tabulate==0.9.0
RUN pip install tensorboard==2.11.2
RUN pip install tensorboard-data-server==0.6.1
RUN pip install tensorboard-plugin-wit==1.8.1
RUN pip install tensorboardx==2.6
RUN pip install termcolor==2.3.0
RUN pip install terminaltables==3.1.10
RUN pip install tfds-nightly==4.4.0.dev202201080107
RUN pip install threadpoolctl==3.1.0
RUN pip install tifffile==2021.11.2
RUN pip install timm==0.6.13
RUN pip install tomli==2.0.1
RUN pip install torch==1.13.0
RUN pip install torchdiffeq==0.2.3
RUN pip install torchmetrics==0.11.4
RUN pip install torchvision==0.15.0
RUN pip install tqdm==4.65.0
RUN pip install ttach==0.0.3
RUN pip install typeguard==4.1.2
RUN pip install typing-extensions==4.7.1
RUN pip install urllib3==1.25.11
RUN pip install visdom==0.2.3
RUN pip install wandb==0.15.5
RUN pip install werkzeug==2.2.3
RUN pip install widgetsnbextension==4.0.7
RUN pip install wilds==2.0.0
RUN pip install wrapt==1.16.0
RUN pip install xlrd==1.2.0
RUN pip install xmltodict==0.13.0
RUN pip install yacs==0.1.8
RUN pip install yapf==0.33.0
RUN pip install yarl==1.9.2
RUN pip install beautifulsoup4==4.11.1
RUN pip install bleach==4.1.0
RUN pip install certifi==2022.12.7
RUN pip install cffi==1.15.1
RUN pip install debugpy==1.5.1
RUN pip install decorator==5.1.1
RUN pip install entrypoints==0.4
RUN pip install jedi==0.18.1
RUN pip install jsonschema==4.16.0
RUN pip install jupyter_client==7.3.5
RUN pip install torchsample
RUN pip install opencv-python
RUN pip install diffusers==0.24.0
RUN pip install accelerate==0.24.1
RUN pip install transformers==4.35.2
RUN pip install openai==1.3.0
RUN pip install nltk==3.8.1
RUN pip install gpustat==1.1.1
RUN pip install sentence-transformers 

COPY ./fonts/* /opt/conda/lib/python3.10/site-packages/matplotlib/mpl-data/fonts/ttf/
